//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_protocolo_historico
    {
        public int IDPROTOCOLOHISTORICO { get; set; }
        public int IDUSUARIORESPONSAVEL { get; set; }
        public Nullable<int> IDPROTOCOLO { get; set; }
        public Nullable<int> IDDEPARTAMENTO { get; set; }
        public string DETALHAMENTO { get; set; }
    
        public virtual tb_protocolo tb_protocolo { get; set; }
    }
}
