//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_protocolo_status
    {
        public tb_protocolo_status()
        {
            this.tb_protocolo = new HashSet<tb_protocolo>();
        }
    
        public int IDSTATUS { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<tb_protocolo> tb_protocolo { get; set; }
    }
}
