//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int IDUSUARIO { get; set; }
        public string NOME { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
        public string EMAIL { get; set; }
        public string CPFCNPJ { get; set; }
        public string SEXO { get; set; }
        public string FAIXAETARIA { get; set; }
        public string PROFISSAO { get; set; }
        public string DDDTELEFONE { get; set; }
        public string TELEFONE { get; set; }
        public string DDDCELULAR { get; set; }
        public string CELULAR { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string CEP { get; set; }
        public Nullable<int> IDCIDADE { get; set; }
        public Nullable<int> IDSTATUS { get; set; }
        public Nullable<int> IDNIVEL { get; set; }
        public Nullable<int> IDESCOLARIDADE { get; set; }
        public Nullable<int> IDDEPARTAMENTO { get; set; }
        public string OUTRALOCALIDADE { get; set; }
    }
}
